import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("portfolio uses an accessible modular QA map with verified evidence", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const portfolioMap = await readFile(new URL("../app/portfolio-map.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const layout = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");
  const worker = await readFile(new URL("../worker/index.ts", import.meta.url), "utf8");
  const wrangler = await readFile(new URL("../wrangler.jsonc", import.meta.url), "utf8");

  assert.match(page, /PortfolioMap/);
  assert.match(portfolioMap, /Екатерина Дедяшкина/);
  assert.match(portfolioMap, /QA Engineer/);
  assert.match(portfolioMap, /Manual \+ Automation/);
  assert.match(portfolioMap, /portfolioModules/);
  assert.match(portfolioMap, /id: "about"/);
  assert.match(portfolioMap, /id: "experience"/);
  assert.match(portfolioMap, /id: "e2e"/);
  assert.match(portfolioMap, /id: "backend"/);
  assert.match(portfolioMap, /id: "critical"/);
  assert.match(portfolioMap, /id: "l3"/);
  assert.match(portfolioMap, /id: "automation"/);
  assert.match(portfolioMap, /id: "audit"/);
  assert.match(portfolioMap, /id: "stack"/);
  assert.match(portfolioMap, /<dialog/);
  assert.match(portfolioMap, /showModal/);
  assert.match(portfolioMap, /onCancel/);
  assert.match(portfolioMap, /aria-haspopup="dialog"/);
  assert.match(portfolioMap, /aria-expanded={active}/);
  assert.match(portfolioMap, /aria-controls="portfolio-dialog"/);
  assert.match(portfolioMap, /window\.history\.pushState/);
  assert.match(portfolioMap, /window\.addEventListener\("popstate"/);
  assert.match(portfolioMap, /15 Critical/);
  assert.match(portfolioMap, /8 E2E suites/);
  assert.match(portfolioMap, /≈250–833/);
  assert.match(portfolioMap, /Collection Runner/);
  assert.match(portfolioMap, /Product QA \/ UX/);
  assert.match(portfolioMap, /QA Engineer · 3\+ года/);
  assert.match(portfolioMap, /id: "about", number: "01".*position: "north"/);
  assert.match(portfolioMap, /id: "experience", number: "02".*position: "north-east"/);
  assert.match(portfolioMap, /id: "experience", number: "02", title: "Опыт", short: "Product QA"/);
  assert.match(portfolioMap, /id: "e2e", number: "03".*position: "east"/);
  assert.match(portfolioMap, /id: "backend", number: "04".*position: "south-east"/);
  assert.match(portfolioMap, /id: "backend", number: "04", title: "Business Logic \/ Data", short: "Расчёт · PostgreSQL"/);
  assert.match(portfolioMap, /id: "critical", number: "05".*position: "bottom-east"/);
  assert.match(portfolioMap, /id: "critical", number: "05", title: "Critical Defects", short: "Product \/ business risk"/);
  assert.match(portfolioMap, /id: "l3", number: "06".*position: "bottom-west"/);
  assert.match(portfolioMap, /id: "l3", number: "06", title: "Production Diagnostics \/ L3", short: "POS · SAP · SQL"/);
  assert.match(portfolioMap, /id: "automation", number: "07".*position: "south-west"/);
  assert.match(portfolioMap, /id: "automation", number: "07", title: "Integrations \/ Devices", short: "Android · Physical equipment"/);
  assert.match(portfolioMap, /id: "audit", number: "08".*position: "west"/);
  assert.match(portfolioMap, /id: "audit", number: "08", title: "Product QA \/ UX", short: "Admin scenarios"/);
  assert.match(portfolioMap, /id: "stack", number: "09".*position: "north-west"/);
  assert.match(portfolioMap, /<span className="node-number">{module\.number}<\/span>/);
  assert.match(portfolioMap, /function ArrowUpRightIcon\(\)[\s\S]*?className="arrow-up-right"/);
  assert.match(portfolioMap, /className="node-arrow"[\s\S]*?<ArrowUpRightIcon \/>/);
  assert.match(portfolioMap, /d="M5 13 13 5M7 5h6v6"/);
  assert.doesNotMatch(portfolioMap, /↗/);
  assert.match(portfolioMap, />CV <span className="link-arrow"/);
  assert.match(portfolioMap, />Email <span className="link-arrow"/);
  assert.match(portfolioMap, />Telegram <span className="link-arrow"/);
  assert.match(portfolioMap, /<span>{activeModule\.number}<\/span>/);
  assert.match(portfolioMap, /className="dialog-close"/);
  assert.match(portfolioMap, /className="dialog-close-label">Закрыть/);
  assert.match(portfolioMap, /className="dialog-close-icon"/);
  assert.match(styles, /\.arrow-up-right[^}]*stroke-width: 1\.35/);
  assert.match(styles, /\.dialog-close-icon[^}]*border: 1px solid rgba/);
  assert.match(styles, /\.dialog-close-label \{ display: none; \}/);
  assert.match(styles, /\.dialog-close:focus, \.dialog-close:focus-visible \{ outline: none; box-shadow: none; \}/);
  assert.match(portfolioMap, /Астана · GMT\+5 · Гражданство РФ/);
  assert.match(portfolioMap, /Рассматриваю позиции QA Engineer/);
  assert.match(portfolioMap, /локализую дефекты на стыке приложения, данных, интеграций и инфраструктуры/);
  assert.match(portfolioMap, /Есть опыт системной диагностики и работы с инфотерминалами, включая устройства с биометрической идентификацией/);
  assert.match(portfolioMap, /автоматизирую UI\/E2E-сценарии на Python с Selenium и Playwright/);
  assert.match(portfolioMap, /Рассматриваю позиции QA Engineer Middle · Manual \+ Automation · Web \/ API \/ Backend/);
  assert.match(portfolioMap, /Commercial QA experience/);
  assert.match(portfolioMap, /QA Middle/);
  assert.match(portfolioMap, /E2E · Business logic · Data/);
  assert.match(portfolioMap, /Astana, Kazakhstan · GMT\+5 · Remote \/ relocation/);
  assert.match(portfolioMap, /Автоматизировала критический пользовательский путь B2B-платформы/);
  assert.match(portfolioMap, /Наборы запускаются каждое утро и дают независимый regression-сигнал после изменений продукта/);
  assert.match(portfolioMap, /"Login", "Profile", "Assignments", "Session", "Assessment", "Result \/ Report", "Logout"/);
  assert.match(portfolioMap, /Ежедневный контроль/);
  assert.match(portfolioMap, /Автотесты выявляют падения критического пути после релизов и небольших изменений, в том числе когда отдельный ручной regression не запускался/);
  assert.match(portfolioMap, /Диагностика падения/);
  assert.match(portfolioMap, /При ошибке сохраняются screenshots и logs, которые дают контекст сбоя и помогают быстрее перейти к локализации причины/);
  assert.match(portfolioMap, /Отчётность/);
  assert.match(portfolioMap, /После прогона доступен отчёт с результатами и падениями: видно, какой сценарий сломался и с какого участка начинать анализ/);
  assert.match(portfolioMap, /Python · Selenium · Playwright/);
  assert.match(portfolioMap, /8 E2E suites · daily run/);
  assert.match(portfolioMap, /"Change", "Daily E2E", "Failure", "Screenshot \/ Logs", "Diagnosis"/);
  assert.match(portfolioMap, /screenshots, logs и отчёт дают данные для диагностики; причину сбоя локализую я/);
  assert.doesNotMatch(portfolioMap, /Полный ручной E2E занимал около рабочего дня|≈рабочий день|Автоматизация освобождает повторяющееся ручное время/);
  assert.match(portfolioMap, /Проверяю корректность результата по всей цепочке — от методологии и входных данных до backend-расчёта, PostgreSQL и итогового клиентского отчёта/);
  assert.match(portfolioMap, /"Методология", "Тестовые данные", "API \/ Backend", "PostgreSQL", "Расчёт", "Отчёт"/);
  assert.match(portfolioMap, /Ожидаемый результат/);
  assert.match(portfolioMap, /Разбираю методологию и определяю, какой результат система должна получить на контрольных данных/);
  assert.match(portfolioMap, /Проверка по слоям/);
  assert.match(portfolioMap, /Сверяю API-ответы, серверную логику, данные PostgreSQL и логи, чтобы найти уровень, на котором возникает расхождение/);
  assert.match(portfolioMap, /Итог для клиента/);
  assert.match(portfolioMap, /Проверяю, что рассчитанные значения корректно доходят до финального результата и отчёта без искажений/);
  assert.match(portfolioMap, /Клиентские кейсы/);
  assert.match(portfolioMap, /Воспроизвожу спорный результат на данных клиента и прохожу расчёт по слоям, чтобы определить источник расхождения: входные данные, методология, backend-логика или формирование отчёта/);
  assert.doesNotMatch(portfolioMap, /const flow = \["UI", "API", "Backend", "PostgreSQL", "Расчёт", "Результат"\]/);
  assert.match(portfolioMap, /15 Critical до production/);
  assert.match(portfolioMap, /User flow · Assessment integrity · Multi-tenant data/);
  assert.match(portfolioMap, /Потеря пользовательского сценария/);
  assert.match(portfolioMap, /Пользователь мог случайно ввести некорректный год и вместо validation error попадал в 404-состояние/);
  assert.match(portfolioMap, /очистка cookies\/cache и hard reload/);
  assert.match(portfolioMap, /Повторяемость проблемы до восстановления состояния браузера/);
  assert.match(portfolioMap, /Integrity assessment/);
  assert.match(portfolioMap, /В тесте способностей пользователь мог копировать содержимое задания/);
  assert.match(portfolioMap, /Потенциальное влияние на валидность результатов тестирования/);
  assert.match(portfolioMap, /Multi-tenant data integrity/);
  assert.match(portfolioMap, /Массовый импорт в неверную организацию/);
  assert.match(portfolioMap, /аккаунты создавались в дефолтной организации/);
  assert.match(portfolioMap, /Нарушение multi-tenant логики продукта/);
  assert.match(portfolioMap, /Почему Critical/);
  assert.match(portfolioMap, /Критичность оцениваю не только по внешнему проявлению дефекта, но и по его влиянию на пользовательский сценарий, корректность результата и данные, а также по сложности восстановления после релиза/);
  assert.match(portfolioMap, /Диагностировала проблемы production retail-инфраструктуры: POS, SAP и внутренних систем/);
  assert.match(portfolioMap, /Работала с Active Directory, SQL, логами и мониторингом, локализовала источник проблемы и передавала воспроизводимые дефекты на дальнейший разбор/);
  assert.match(portfolioMap, /"Обращение", "Воспроизведение", "Диагностика", "Локализация", "Решение \/ Эскалация"/);
  assert.match(portfolioMap, /Системная диагностика/);
  assert.match(portfolioMap, /Active Directory · SQL · logs · monitoring/);
  assert.match(portfolioMap, /Production-среда/);
  assert.match(portfolioMap, /POS · SAP · retail infrastructure · internal systems/);
  assert.match(portfolioMap, /Эскалация дефекта/);
  assert.match(portfolioMap, /сценарий воспроизведения · фактический результат · технические данные для разбора/);
  assert.match(portfolioMap, /<Metric value="~1 000" label="обращений в месяц" tone="team"/);
  assert.match(portfolioMap, /<Metric value="98–99%" label="закрытие заявок" tone="team"/);
  assert.match(portfolioMap, /<Metric value="~97% смен" label="1-е место во внутреннем daily SLA-рейтинге" tone="personal"/);
  assert.doesNotMatch(portfolioMap, /Командная нагрузка и closure rate отделены от моего личного результата по SLA/);
  assert.match(portfolioMap, /Тестировала сценарии на стыке программного обеспечения, Android-устройств и физического оборудования: от API и мобильного приложения до терминалов и систем идентификации/);
  assert.match(portfolioMap, /"Backend \/ API", "Android app", "Device", "Physical action", "Result"/);
  assert.match(portfolioMap, /API \/ Integrations/);
  assert.match(portfolioMap, /JWT · QR-сценарии · backend interaction/);
  assert.match(portfolioMap, /реальные устройства · эмуляторы · ADB · Kotlin \/ Espresso/);
  assert.match(portfolioMap, /Physical equipment/);
  assert.match(portfolioMap, /инфотерминалы · турникетные системы · биометрическая идентификация/);
  assert.match(portfolioMap, /Проверяла не только поведение приложения, но и полный интеграционный сценарий между ПО и физическим оборудованием/);
  assert.doesNotMatch(portfolioMap, /Автоматизировала PowerShell-скриптом операцию подготовки и копирования установочных файлов SAP GUI и DLL-библиотек для магазинов/);
  assert.match(portfolioMap, /Анализировала административные пользовательские сценарии: фильтрацию, массовый выбор, статусы, блокировку и архивацию/);
  assert.match(portfolioMap, /Выявляла точки, где интерфейс повышал риск ошибки, и формулировала предложения по улучшению/);
  assert.match(portfolioMap, /выявленные проблемы и предложения были оформлены как задачи на доработку/);
  assert.match(portfolioMap, /audit-lightbox/);
  assert.match(portfolioMap, /role="dialog"/);
  assert.match(portfolioMap, /onMouseDown/);
  assert.match(portfolioMap, /data-lightbox-close/);
  assert.match(portfolioMap, /lightboxClose\.click/);
  assert.match(portfolioMap, /event.key !== "Tab"/);
  assert.match(portfolioMap, /ArrowLeft/);
  assert.match(portfolioMap, /ArrowRight/);
  assert.match(portfolioMap, /Открыть изображение/);
  assert.match(portfolioMap, /respondents-audit-cropped\.png/);
  assert.match(portfolioMap, /before-after-cropped\.png/);
  assert.match(portfolioMap, /QA \/ Testing/);
  assert.match(portfolioMap, /API \/ Data/);
  assert.match(portfolioMap, /Mobile \/ Devices/);
  assert.match(portfolioMap, /Diagnostics \/ Monitoring/);
  assert.match(portfolioMap, /Infrastructure \/ Enterprise/);
  assert.match(portfolioMap, /Python · Selenium · Playwright/);
  assert.match(portfolioMap, /Postman · Swagger\/OpenAPI/);
  assert.match(portfolioMap, /JavaScript.*разработка автотестов/s);
  assert.match(portfolioMap, /JUnit.*поддержка существующих тестов/s);
  assert.match(portfolioMap, /PowerShell.*operational automation/s);
  assert.match(portfolioMap, /Active Directory/);
  assert.match(portfolioMap, /Grafana.*Loki.*Zabbix/s);
  assert.doesNotMatch(portfolioMap, /<strong>Практика:<\/strong>/);
  assert.match(portfolioMap, /<small>3\+ года в QA<\/small>/);
  assert.doesNotMatch(portfolioMap, /Product QA → L3|3\+ года QA \/ L3/);
  assert.match(portfolioMap, /Предыдущее изображение/);
  assert.match(portfolioMap, /Следующее изображение/);
  assert.match(portfolioMap, /requestAnimationFrame/);
  assert.match(portfolioMap, /Методология тестов и расчётная бизнес-логика/);
  assert.match(portfolioMap, /UI\/UX-аудит административных сценариев · Карта улучшений/);
  assert.match(portfolioMap, /API testing · Postman collections · JS test scripts · Collection Runner/);
  assert.match(portfolioMap, /results: \["8 E2E suites · ежедневный автопрогон", "15 Critical до production"\]/);
  assert.match(portfolioMap, /Active Directory · POS · SAP · Внутренние системы/);
  assert.match(portfolioMap, /Подготовка и копирование установочных файлов SAP GUI и DLL-библиотек/);
  assert.match(portfolioMap, /30–60 мин на один магазин/);
  assert.match(portfolioMap, /Ручная подготовка и копирование установочных файлов SAP GUI и DLL-библиотек\./);
  assert.match(portfolioMap, /10–15 мин на один магазин/);
  assert.match(portfolioMap, /После PowerShell-автоматизации\./);
  assert.match(portfolioMap, /label: "Экономия времени"/);
  assert.match(portfolioMap, /≈250–833 человеко-часов/);
  assert.match(portfolioMap, /Сэкономленного ручного труда на каждые 1 000 магазинов при одном массовом обновлении\./);
  assert.match(portfolioMap, /15–50 мин экономии на один магазин × 1 000 магазинов = ≈250–833 человеко-часов/);
  assert.match(portfolioMap, /До автоматизации: 500–1 000 человеко-часов \/ 1 000 магазинов/);
  assert.match(portfolioMap, /После автоматизации: ≈167–250 человеко-часов \/ 1 000 магазинов/);
  assert.match(portfolioMap, /Человеко-часы — суммарные трудозатраты специалистов; при параллельной работе календарное время могло быть меньше\./);
  assert.doesNotMatch(portfolioMap, /Вручную · 30–60|После PowerShell · 10–15|label: "Масштаб"/);
  assert.match(portfolioMap, /~97% смен — 1-е место во внутреннем ежедневном SLA-рейтинге/);
  assert.match(portfolioMap, /Web \/ Backend/);
  assert.match(portfolioMap, /CRM · Backend\/API · Интеграции/);
  assert.match(portfolioMap, /JavaScript — разработка автотестов · JUnit — поддержка существующих/);
  assert.match(portfolioMap, /API \/ инструменты/);
  assert.match(portfolioMap, /Postman · Swagger · Docker/);
  assert.match(portfolioMap, /Диагностика дефектов и пользовательских обращений/);
  assert.match(portfolioMap, /Android \/ терминалы/);
  assert.match(portfolioMap, /JWT \/ QR-сценарии/);
  assert.match(portfolioMap, /150\+ Major \/ Minor/);
  assert.match(portfolioMap, /найдено и заведено дефектов/);
  assert.match(portfolioMap, /E2E-автоматизация/);
  assert.match(portfolioMap, /69 человеко-часов ручного E2E в месяц/);
  assert.match(portfolioMap, /До 69 ч\/месяц повторяющегося ручного E2E переведено в автоматические проверки/);
  assert.match(portfolioMap, /Частота полной E2E-проверки выросла в 2,5 раза/);
  assert.match(portfolioMap, /75–87,5%/);
  assert.match(portfolioMap, /Масштаб роли/);
  assert.match(portfolioMap, /2 продуктовых направления/);
  assert.match(portfolioMap, /Глубокая диагностика/);
  assert.match(portfolioMap, /Передача знаний/);
  assert.match(portfolioMap, /Инфотерминалы · Физические устройства · Биометрическая идентификация/);
  assert.doesNotMatch(portfolioMap, /Перевела критический E2E из ручной проверки длительностью около рабочего дня/);
  assert.doesNotMatch(portfolioMap, /Вела два направления: Web\/Backend и Android с физическим оборудованием/);
  assert.doesNotMatch(portfolioMap, /69 часов сэкономлено/);
  assert.doesNotMatch(portfolioMap, /QA\/UI\/UX-аудит|Postman JS · Collection Runner|≈8 часов|примерно 2 раза|≈69 человеко-часов|Machine runtime ≈|До ≈69|примерно в 2,5 раза|примерно на 75–87,5%/);
  assert.match(layout, /Web, API, Backend, Automation/);
  assert.match(worker, /Response\.redirect\(requestUrl\.toString\(\), 308\)/);
  assert.match(worker, /hostname === "localhost"/);
  assert.match(worker, /env\.ASSETS\s*\?\s*await env\.ASSETS\.fetch\(request\)/);
  assert.match(worker, /assetResponse\.status !== 404/);
  assert.match(worker, /vinext\.static-file-signal/);
  assert.match(worker, /Object\.defineProperty\(securedResponse, STATIC_FILE_SIGNAL/);
  assert.match(worker, /Strict-Transport-Security/);
  assert.match(wrangler, /"preview_urls": false/);

  assert.doesNotMatch(portfolioMap, /release \/ quality-gate|24<\/strong>|98%<\/strong>|Мем-режим|Мем-стена|Off \/ Lite \/ Spicy/);
  assert.doesNotMatch(portfolioMap, /165\+|4 продуктовых контура|5 направлений автоматизации/);
  assert.doesNotMatch(portfolioMap, /Подтверждённые данные|QA-effort|specialist-hours|Product QA audit|production risk/);
  assert.doesNotMatch(portfolioMap, /локализую причины дефектов|критические UI\/E2E-сценарии/);
  assert.doesNotMatch(`${page}${portfolioMap}${layout}`, /codex-preview|_sites-preview|Starter Project/);
});
